x=1
try:
    print(x)
except:
    print("Aception ocurred")    